### ISSUE TITLE
Subtasks checkbox not indenting on board

### ISSUE THREAD

**Issue by gjdreisbach** [roovo/obsidian-card-board#240]
Hi, so far loving the plugin.  However my subtasks check box does not appear to be indented when I look at the board.  It looks like the text is indendent but not the check box.  I tried disabling all other community plugins but it didn't fix the issue

The code I have input is as follows:
- [ ] To do Penguin #todo
	 - [ ] See if there is any tuning I need to do in order to have these run faster 
	 - [ ] Write bash scripts
		 - [ ] Individual for each mesh file
		 - [ ] Main bash that calls all of the job files

How they appear in the note:
![image](https://github.com/user-attachments/assets/7a3b8f04-efe2-4afb-8f61-7d77f6ec8697)

How they appear in the board:
![image](https://github.com/user-attachments/assets/81cac594-b087-414e-bcf6-52369872e4db)
