### ISSUE TITLE
Show FIlter Tags option to ignore subtask tags when hiding

### ISSUE THREAD

**Issue by roovo** [roovo/obsidian-card-board#95]
So I can show/hide cards with matching tags on subtasks separately to the behavior for tasks with only matching tags on the top level task.

Proposed implementation steps (added 3rd Dec 22) this is for teg boards:

- [x] leave all sub-task tags inline (don't place them at the top of the card)
- [x] only show a task in a tag board column if it has either
  - a matching tag at the top level (and the top level task is not marked as complete)
  - a matching tag for one of the sub-tasks and that sub-task is not marked as complete
- [x] the "Other" column should contain any card on which there are tagged incomplete tasks (including sub-tasks) where the tag is not one defined for any of the columns on that board.
- [x] on any tag board where a card would have appeared had it not been marked as completed (at either task or sub-task level), it should appear in the completed column if it is not in any of the columns on that board.
- [x] add the same behavior for DateBoards
- [x] provide an option for choosing whether to include sub-tasks when filtering by tag
- [x] docs

**Comment by juestchaos** [comment]
+1 for this.

**Comment by roovo** [comment]
The use-case I am thinking of is where I have a date board which I want to contain tasks that are primarily need to be on my radar.  As I want to exclude things that I need to pass on to others I have it set up to ignore `#people/` tags via a board level deny filter.  This means however if I have a task which I want to track where the sub-tasks are tagged with other people:

```
- [ ] something that needs doing
    - [ ] ask #people/gary to do something
    - [ ] then I will need #people/guru approval
    - [ ] and will need to let #people/ravi know
    - [ ] send an email round to the team
```

it won't appear on my date board :(

So I would like to be able to only filter on (in this example) `#people/` tasks where the tag is on the top level task.  This means I would see this on my board.

A supplimentry question is whether I should leave tags that appear in sub-tasks inline in the tasks.  This would make it more obvious which subtask is for which person in the above example.  It would also be in line with what happens with notes text indented under a task - i.e. any tags are left where they are.

**Comment by roovo** [comment]
Having re-worked how the boards are set up and the cards are "dealt" into the columns and looked at this, I am minded to not have an option for this at all, but to just make it so that tag filters only work on tags that belong to the top level task -> so tags for sub tasks are not taken into account when filtering which cards can appear on a board.

**Comment by roovo** [comment]
> Having re-worked how the boards are set up and the cards are "dealt" into the columns and looked at this, I am minded to not have an option for this at all, but to just make it so that tag filters only work on tags that belong to the top level task -> so tags for sub tasks are not taken into account when filtering which cards can appear on a board.

Scrap that - better to stick with the original plan :)

**Comment by roovo** [comment]
Just released in: [0.7.0](https://github.com/roovo/obsidian-card-board/releases/tag/0.7.0)

There are now options to apply tag filters to either top level tasks, sub-tasks, or both...
